#Deploy the pod
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: trader
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: trader
        solution: stock-trader
        version: v1
    spec:
      containers:
      - name: trader
#       Note: this manifests/deploy.yaml will be used when we want to deploy this directly using kubectl or a helm chart. 
#             Microclimate uses the Charts folder so we can actually have both options
        # image: ibmstocktrader/trader:basicregistry # Docker Hub with basic registry sign in
        image: mycluster.icp:8500/default/trader:pr # IBM Cloud Private
        #image: registry.ng.bluemix.net/stock_trader/trader:latest # IBM Container Service
        env:
          # - name: OIDC_NAME
          #   valueFrom:
          #     secretKeyRef:
          #       name: oidc
          #       key: name
          # - name: OIDC_ISSUER
          #   valueFrom:
          #     secretKeyRef:
          #       name: oidc
          #       key: issuer
          # - name: OIDC_AUTH
          #   valueFrom:
          #     secretKeyRef:
          #       name: oidc
          #       key: auth
          # - name: OIDC_TOKEN
          #   valueFrom:
          #     secretKeyRef:
          #       name: oidc
          #       key: token
          # - name: OIDC_ID
          #   valueFrom:
          #     secretKeyRef:
          #       name: oidc
          #       key: id
          # - name: OIDC_SECRET
          #   valueFrom:
          #     secretKeyRef:
          #       name: oidc
          #       key: secret
          # - name: OIDC_KEY
          #   valueFrom:
          #     secretKeyRef:
          #       name: oidc
          #       key: key
          # - name: OIDC_NODEPORT
          #   valueFrom:
          #     secretKeyRef:
          #       name: oidc
          #       key: nodeport
          - name: JWT_AUDIENCE
            valueFrom:
              secretKeyRef:
                name: jwt 
                key: audience
          - name: JWT_ISSUER
            valueFrom:
              secretKeyRef:
                name: jwt
                key: issuer
        ports:
          - containerPort: 9080
          - containerPort: 9443
        imagePullPolicy: Always
---
#Deploy the service
apiVersion: v1
kind: Service
metadata:
  name: trader-service
  labels:
    app: trader
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 9080
      targetPort: 9080
      nodePort: 32388
    - name: https
      protocol: TCP
      port: 9443
      targetPort: 9443
      nodePort: 32389
  selector:
    app: trader
---
#Configure the ingress
# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: trader-ingress
#   annotations:
#     kubernetes.io/ingress.class: "istio"
# spec:
#   rules:
#   - http:
#       paths:
#       - path: /trader/.*
#         backend:
#           serviceName: trader-service
#           servicePort: 9443
# ---   
#Configure the ingress 
# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   annotations:
#     kubernetes.io/ingress.class: "nginx"
#     ingress.kubernetes.io/app-root: "/trader"
#   name: trader-ingress
# spec:
#   rules:
#   - host:
#     http:
#       paths:
#       - path: /trader
#         backend:
#           serviceName: trader-service
#           servicePort: 9443
